server:
  port: 8088
spring:
  thymeleaf:
    cache: false
paypal:
  mode: sandbox
  client:
    app: Aax1I3MrIzIelwyEA7oSyrT6pdRZG-pjLQjVKypKkCbmVaHFRYU1IgUopu3Fh-N50TC6DVUDGge-jeL6
    secret: EIAaaKcAZ2eLITWuX_PJF--ig4Da8osufWL-Vp-Z9pnV-anq3f31M8PNq35vdo0PjuVfFXtxRklVpKxI